server:
  port: 8082

spring:
    datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/micro_hotel_review
      username: postgres
      password: Rahul@3178


    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    application:
      name: Hotel-Service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka